# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Restore dependencies
      run: msbuild CodePulse.API.sln /t:Restore /p:Configuration=Release
    - name: Build
      run: msbuild CodePulse.API.sln /p:Configuration=Release /p:RestorePackages=false
    - name: Test
      run: dotnet test CodePulse.API/CodePulse.API.csproj --configuration Release --no-build --verbosity normal
